development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://convocord.herokuapp.com:6379/1" } %>
  channel_prefix: convocord_production
  # url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
